
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/personal"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/.infrastructure"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
