name: AWS Service CI/CD
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: Build website
        working-directory: personal
        run: | 
          yarn
          yarn build
      - name: Deploy cdk
        working-directory: .infrastructure
        run: | 
          yarn
          yarn cdk synth
          yarn cdk deploy --all --require-approval never
          